let currentLang='zh';let poems={};let config={};const App={DataManager:{async loadData(){try{const response=await fetch('./data/data.json');const data=await response.json();poems=data.poems;config=data.config;return data;}catch(error){console.error('Failed to load data:',error);poems={zh:[],en:[]};config={zh:{},en:{}};return{poems,config};}}},LanguageManager:{changeLanguage(lang){if(!lang||(lang!=='zh'&&lang!=='en')){console.warn('Invalid language:',lang);return;}
console.log('Changing language from',currentLang,'to',lang);currentLang=lang;this.updateContent();this.updateLanguageButton();App.PoemManager.displayCurrentPoem();console.log('Language changed successfully to:',currentLang);},updateContent(){if(!config[currentLang]){console.warn('Config not found for language:',currentLang);return;}
const langConfig=config[currentLang];const titleElement=document.querySelector('#message h1');if(titleElement&&langConfig.title){titleElement.textContent=langConfig.title;}
App.Utils.updateGreeting();this.updateNavigationText(langConfig);},updateNavigationText(langConfig){if(!langConfig.navigation)return;const blogLink=document.querySelector('.go2blogwork a[href*="blog"]');const workLink=document.querySelector('.go2blogwork a[href*="work"]');if(blogLink&&langConfig.navigation.blog){blogLink.textContent=langConfig.navigation.blog;}
if(workLink&&langConfig.navigation.work){workLink.textContent=langConfig.navigation.work;}},updateLanguageButton(){const languageSwitcher=document.querySelector('.language-switcher');if(!languageSwitcher){console.error('Language switcher container not found');return;}
const languageButtons=languageSwitcher.querySelectorAll('a:not([href*="eve.ihogu.com"])');languageButtons.forEach(btn=>btn.remove());const langButton=document.createElement('a');langButton.href='#';langButton.className='language-button';if(currentLang==='zh'){langButton.innerHTML='🌐English';langButton.dataset.targetLang='en';}else{langButton.innerHTML='🇨🇳中文';langButton.dataset.targetLang='zh';}
langButton.addEventListener('click',(e)=>{e.preventDefault();e.stopPropagation();const targetLang=e.currentTarget.dataset.targetLang;console.log('Language button clicked, switching to:',targetLang);this.changeLanguage(targetLang);});languageSwitcher.appendChild(langButton);console.log('Language button updated for lang:',currentLang);}},PoemManager:{currentIndex:0,displayCurrentPoem(){if(!poems[currentLang]||poems[currentLang].length===0){console.warn('No poems available for language:',currentLang);const fallbackLang=currentLang==='zh'?'en':'zh';if(poems[fallbackLang]&&poems[fallbackLang].length>0){const poemList=poems[fallbackLang];this.currentIndex=Math.min(this.currentIndex,poemList.length-1);this.displayPoem(poemList[this.currentIndex]);}
return;}
const poemList=poems[currentLang];if(this.currentIndex>=poemList.length){this.currentIndex=0;}
console.log('Displaying poem for language:',currentLang,'index:',this.currentIndex);this.displayPoem(poemList[this.currentIndex]);},showRandomPoem(){if(!poems[currentLang]||poems[currentLang].length===0){console.warn('No poems available for language:',currentLang);return;}
const poemList=poems[currentLang];this.currentIndex=Math.floor(Math.random()*poemList.length);this.displayPoem(poemList[this.currentIndex]);},showNextPoem(){if(!poems[currentLang]||poems[currentLang].length===0){return;}
const poemList=poems[currentLang];this.currentIndex=(this.currentIndex+1)%poemList.length;this.displayPoem(poemList[this.currentIndex]);},showPrevPoem(){if(!poems[currentLang]||poems[currentLang].length===0){return;}
const poemList=poems[currentLang];this.currentIndex=(this.currentIndex-1+poemList.length)%poemList.length;this.displayPoem(poemList[this.currentIndex]);},displayPoem(poem){if(!poem)return;const container=document.querySelector('.main-shici');if(!container)return;container.innerHTML='';if(poem.title||poem.author){const titleP=document.createElement('p');titleP.style.fontWeight='bold';titleP.style.fontSize='20px';titleP.style.marginBottom='15px';titleP.style.color='#2c3e50';let titleText='';if(poem.title)titleText+=poem.title;if(poem.author)titleText+=(titleText?' - ':'')+poem.author;titleP.textContent=titleText;container.appendChild(titleP);}
const hr=document.createElement('hr');container.appendChild(hr);const article=document.createElement('div');article.className='article chushibiao';article.style.display='block';const poemContent=poem.content||poem.item;if(poemContent){const lines=Array.isArray(poemContent)?poemContent:poemContent.split('\n');lines.forEach(line=>{if(line.trim()){const p=document.createElement('p');p.textContent=line.trim();article.appendChild(p);}});}
container.appendChild(article);this.addNavigationButtons(container);},addNavigationButtons(container){const navDiv=document.createElement('div');navDiv.style.textAlign='center';navDiv.style.marginTop='10px';navDiv.style.padding='8px';const prevBtn=document.createElement('button');prevBtn.textContent=currentLang==='zh'?'上一篇':'Previous';prevBtn.onclick=()=>this.showPrevPoem();this.styleButton(prevBtn);const nextBtn=document.createElement('button');nextBtn.textContent=currentLang==='zh'?'下一篇':'Next';nextBtn.onclick=()=>this.showNextPoem();this.styleButton(nextBtn);const randomBtn=document.createElement('button');randomBtn.textContent=currentLang==='zh'?'随机':'Random';randomBtn.onclick=()=>this.showRandomPoem();this.styleButton(randomBtn);navDiv.appendChild(prevBtn);navDiv.appendChild(randomBtn);navDiv.appendChild(nextBtn);container.appendChild(navDiv);},styleButton(button){button.style.cssText=`margin:0 5px;padding:6px 12px;background:linear-gradient(45deg,#689f38,#4a7c3a);color:white;border:none;border-radius:15px;cursor:pointer;font-weight:500;font-size:14px;transition:all 0.3s ease;box-shadow:0 4px 15px rgba(104,159,56,0.4);`;button.onmouseover=function(){this.style.background='linear-gradient(45deg, #5d8a2f, #3e5e2a)';this.style.boxShadow='0 6px 20px rgba(104, 159, 56, 0.6)';this.style.transform='translateY(-2px)';};button.onmouseout=function(){this.style.background='linear-gradient(45deg, #689f38, #4a7c3a)';this.style.boxShadow='0 4px 15px rgba(104, 159, 56, 0.4)';this.style.transform='translateY(0)';};}},Utils:{getTimeGreeting(){const hour=new Date().getHours();const greetings=config[currentLang]?.greetings;if(!greetings)return'';if(hour>=5&&hour<12){return greetings.morning||'';}else if(hour>=12&&hour<18){return greetings.afternoon||'';}else{return greetings.evening||'';}},updateGreeting(){const timeGreeting=this.getTimeGreeting();const welcomeConfig=config[currentLang]?.welcome||'';const welcomeElement=document.getElementById('welcome');if(welcomeElement){let combinedGreeting='';if(timeGreeting&&welcomeConfig){combinedGreeting=`${timeGreeting}${welcomeConfig}`;}else if(timeGreeting){combinedGreeting=timeGreeting;}else if(welcomeConfig){combinedGreeting=welcomeConfig;}
welcomeElement.textContent=combinedGreeting;}},updateCurrentYear(){const currentYear=new Date().getFullYear();const copyrightElement=document.querySelector('.icp p');if(copyrightElement){copyrightElement.textContent=`© ${currentYear}Harry Work.All rights reserved.`;}}},async init(){try{console.log('Starting app initialization...');await this.DataManager.loadData();console.log('Data loaded:',{poems:Object.keys(poems),config:Object.keys(config)});this.LanguageManager.changeLanguage('zh');this.PoemManager.showRandomPoem();this.Utils.updateGreeting();this.Utils.updateCurrentYear();const languageSwitcher=document.querySelector('.language-switcher');if(languageSwitcher){console.log('Language switcher found:',languageSwitcher);console.log('Current buttons:',languageSwitcher.querySelectorAll('a'));}else{console.error('Language switcher not found!');}
console.log('App initialized successfully');}catch(error){console.error('Failed to initialize app:',error);}}};function changeLanguage(lang){App.LanguageManager.changeLanguage(lang);App.PoemManager.showRandomPoem();App.Utils.updateGreeting();}
document.addEventListener('DOMContentLoaded',function(){App.init();});window.addEventListener('load',function(){console.log('Page fully loaded');});